# Generated by Django 4.2.4 on 2024-01-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='degree',
            field=models.IntegerField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')]),
        ),
    ]
