# Generated by Django 4.2.4 on 2024-01-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_portfolio_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='degree',
            field=models.IntegerField(choices=[('Junior', 'junior'), ('Middle', 'middle'), ('Senior', 'senior')]),
        ),
    ]
